locale=en_US
dist="forky"
profiles="workstation server"
debian_mirror="http://deb.debian.org/debian/"
mirror_components="main non-free-firmware"
ignore_missing_checksums="true"

export ARCH=amd64
export DISKTYPE=DVD
export MAXCDS=1
export INSTALLER_CD=2

export NONFREE=1
export NONFREE_COMPONENTS="contrib non-free non-free-firmware"

export OMIT_MANUAL=1

